"""邮件发送 — 将 Top10 分析报告推送到用户邮箱"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date
import pandas as pd
import streamlit as st


def _get_smtp_config() -> tuple[str, int, str, str]:
    """从 secrets 读取 SMTP 配置"""
    return (
        st.secrets.get("SMTP_HOST", ""),
        int(st.secrets.get("SMTP_PORT", 465)),
        st.secrets.get("SMTP_USER", ""),
        st.secrets.get("SMTP_PASS", ""),
    )


def smtp_configured() -> bool:
    host, _, user, pwd = _get_smtp_config()
    return bool(host and user and pwd)


def build_email_html(top10_df: pd.DataFrame, summary: str = "",
                     model_name: str = "") -> str:
    """构建 HTML 格式的邮件正文"""
    today_str = date.today().strftime("%Y-%m-%d")

    # 卡片行
    cards_html = ""
    for i, (_, row) in enumerate(top10_df.head(10).iterrows(), 1):
        score = row.get("综合评分", 0)
        name = row.get("股票名称", "")
        code = row.get("代码", "")
        price = row.get("最新价", 0)
        change = row.get("涨跌幅", 0)
        advice = row.get("短线建议", "")
        industry = row.get("行业", "")
        s_fund = row.get("基本面", "")
        s_theme = row.get("题材热度", "")
        s_tech = row.get("技术面", "")

        if score >= 8:
            border = "#22c55e"
        elif score >= 6:
            border = "#6366f1"
        else:
            border = "#f97316"

        change_color = "#22c55e" if change >= 0 else "#ef4444"
        change_sign = "+" if change >= 0 else ""

        advice_colors = {
            "强烈推荐": "#dc2626", "推荐": "#16a34a",
            "观望": "#d97706", "回避": "#6b7280",
        }
        adv_color = advice_colors.get(advice, "#6b7280")

        sub_scores = ""
        if s_fund or s_theme or s_tech:
            sub_scores = f"""<div style="font-size:12px;color:#6b7280;margin-top:4px;">
                基本面 {s_fund or '-'} | 题材 {s_theme or '-'} | 技术面 {s_tech or '-'}
            </div>"""

        cards_html += f"""
        <div style="border:2px solid {border};border-radius:12px;padding:12px 16px;margin:8px 0;">
            <div style="display:flex;justify-content:space-between;align-items:center;">
                <div>
                    <span style="font-size:16px;font-weight:800;">#{i} {name}</span>
                    <span style="font-size:12px;color:#6b7280;margin-left:6px;">{code}</span>
                    <span style="font-size:12px;color:#6b7280;margin-left:6px;">{industry}</span>
                </div>
                <span style="background:{border}22;color:{border};border-radius:20px;
                    padding:2px 12px;font-weight:800;font-size:14px;">{score}/10</span>
            </div>
            <div style="font-size:13px;color:#6b7280;margin-top:6px;">
                💰 {price:.2f}元 &nbsp;
                <span style="color:{change_color};font-weight:600;">{change_sign}{change:.2f}%</span>
                &nbsp; <span style="color:{adv_color};font-weight:700;">{advice}</span>
            </div>
            {sub_scores}
        </div>"""

    # 完整 HTML
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:'Microsoft YaHei',sans-serif;max-width:640px;margin:0 auto;padding:20px;background:#f6f8ff;">

<div style="background:linear-gradient(135deg,#6366f1,#a855f7);color:#fff;
    border-radius:16px;padding:20px;text-align:center;">
    <h1 style="margin:0;font-size:22px;">🏆 每日 Top 10 精选</h1>
    <p style="margin:4px 0 0;opacity:0.9;">{today_str} | 模型：{model_name}</p>
</div>

<div style="margin:16px 0;">
{cards_html}
</div>

{"<div style='background:#fff;border-radius:12px;padding:16px;margin:16px 0;'>"
 "<h3 style='margin:0 0 8px;color:#1e1b4b;'>📝 每日总结</h3>"
 + summary.replace(chr(10), '<br>') +
 "</div>" if summary else ""}

<div style="text-align:center;color:#9ca3af;font-size:11px;margin-top:20px;">
    ⚠️ 本报告仅供学习研究，不构成投资建议。<br>
    Generated by Stock Top 10 · 立花道雪
</div>
</body></html>"""


def send_report_email(recipient: str, top10_df: pd.DataFrame,
                      summary: str = "", model_name: str = "") -> tuple[bool, str]:
    """发送 Top10 报告邮件"""
    host, port, user, pwd = _get_smtp_config()
    if not host or not user or not pwd:
        return False, "SMTP 未配置，请在 Secrets 中添加 SMTP_HOST/SMTP_USER/SMTP_PASS"

    today_str = date.today().strftime("%Y-%m-%d")
    subject = f"🏆 每日Top10精选 — {today_str}"

    html_body = build_email_html(top10_df, summary, model_name)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        if port == 465:
            with smtplib.SMTP_SSL(host, port, timeout=15) as server:
                server.login(user, pwd)
                server.sendmail(user, recipient, msg.as_string())
        else:
            with smtplib.SMTP(host, port, timeout=15) as server:
                server.starttls()
                server.login(user, pwd)
                server.sendmail(user, recipient, msg.as_string())
        return True, "发送成功"
    except Exception as e:
        return False, f"发送失败：{e}"
